# Generated by Django 3.0.5 on 2020-04-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_auto_20200430_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
