# Generated by Django 3.0.5 on 2020-05-04 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0010_auto_20200504_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendlist',
            old_name='friends',
            new_name='friend',
        ),
        migrations.RenameField(
            model_name='friendlist',
            old_name='profile',
            new_name='user',
        ),
    ]
