# Generated by Django 3.0.5 on 2020-05-04 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0011_auto_20200504_0123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendlist',
            old_name='friend',
            new_name='profile',
        ),
    ]
