# Generated by Django 3.0.5 on 2020-05-05 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0012_auto_20200504_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='user',
        ),
        migrations.AddField(
            model_name='friendlist',
            name='friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friend_profile', to='details.Profile'),
        ),
    ]
