# Generated by Django 3.0.5 on 2020-05-05 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0013_auto_20200505_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_profile', to='details.Profile'),
        ),
    ]
