# Generated by Django 3.0.5 on 2020-05-05 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('details', '0014_auto_20200505_0614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='friend',
        ),
        migrations.AddField(
            model_name='friendlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendlist',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='details.Profile'),
        ),
    ]
