# Generated by Django 3.0.4 on 2020-05-05 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0015_auto_20200505_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='user',
        ),
        migrations.AddField(
            model_name='friendlist',
            name='friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friend_profile', to='details.Profile'),
        ),
        migrations.AlterField(
            model_name='friendlist',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_profile', to='details.Profile'),
        ),
    ]
