# Generated by Django 3.0.5 on 2020-05-06 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0017_auto_20200506_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendlist',
            old_name='profile',
            new_name='friend_profile',
        ),
    ]
