# Generated by Django 3.0.5 on 2020-05-06 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('details', '0019_auto_20200506_0123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendlist',
            old_name='user',
            new_name='profile1',
        ),
        migrations.RemoveField(
            model_name='friendlist',
            name='friend_profile',
        ),
        migrations.AddField(
            model_name='friendlist',
            name='profile2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile2', to=settings.AUTH_USER_MODEL),
        ),
    ]
