# Generated by Django 3.0.5 on 2020-05-10 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0021_friendrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='is_accepted',
            new_name='is_friends',
        ),
    ]
