# Generated by Django 3.0.5 on 2020-05-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0022_auto_20200510_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='is_friends',
        ),
        migrations.AddField(
            model_name='friendlist',
            name='is_friends',
            field=models.BooleanField(default=False),
        ),
    ]
