# Generated by Django 3.0.6 on 2020-05-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0023_auto_20200510_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
